% A script that plots data generated by msdanalyzer. Written by Edin Osmanbasic on 4-13-23.
%% Declare Variables
DIFFUSION_CLIP = 0;    % What D R^2 values greater than this do we consider?

SUBDIFF_SORT   = [0.1, 0.5];   % In terms of a <= alpha <= b.
BROWNIAN_SORT  = [0.9, 1.2];   % Like above.

PLOT_MSD_SUBDIFF      = false;  % Plot loglog of subdiff. MSD vs. time lag?
PLOT_MSD_BROWNIAN     = false;  % Plot loglog of Brownian MSD vs. time lag?

PLOT_MEANMSD_SUBDIFF  = false;  % Plot semilogy of subdiff. mean(MSD)s vs. time lag?
PLOT_MEANMSD_BROWNIAN = false;  % Plot semilogy of Brownian mean(MSD)s vs. time lag?

HIST_DIFFUSION = false; % Plot histogram of all diffusion values, with 2 gauss. fits?

%% Load file
[filename,filepath] = uigetfile('*.mat','msdanalyzer file?','MultiSelect','off');
ma = importdata([filepath filename]);

disp('From file: ' + string(filename));

%% Calc alphas and diffusions
idx_good = ma.lfit.r2fit > DIFFUSION_CLIP; % Is R^2 val better than DIFFUSION_CLIP?

idx_subdiff = ma.loglogfit.alpha >= SUBDIFF_SORT(1) ...
            & ma.loglogfit.alpha <= SUBDIFF_SORT(end);

idx_brown   = ma.loglogfit.alpha >= BROWNIAN_SORT(1) ...
            & ma.loglogfit.alpha <= BROWNIAN_SORT(end);

% Subdiffusion
alpha{1,1} = ma.loglogfit.alpha(idx_subdiff & idx_good);
alpha{1,2} = mean(alpha{1,1});
alpha{1,3} =  std(alpha{1,1});

subD   = ma.lfit.a(idx_subdiff & idx_good);
D{1,1} =       subD  / 2 / ma.n_dim;
D{1,2} =  mean(subD) / 2 / ma.n_dim;
D{1,3} =   std(subD) / 2 / ma.n_dim;

fprintf('Mean Subdiff. Alpha = %.3g ± %.3g (mean ± std, N = %d)\n', alpha{1,2}, alpha{1,3}, length(alpha{1,1}));
fprintf('Mean Subdiff. Diffusion = %.3g ± %.3g (mean ± std, N = %d)\n', D{1,2}, D{1,3}, length(D{1,1}));

% Brownian
alpha{2,1} = ma.loglogfit.alpha(idx_brown & idx_good);
alpha{2,2} = mean(alpha{2,1});
alpha{2,3} =  std(alpha{2,1});

brwD   = ma.lfit.a(idx_brown & idx_good);
D{2,1} =       brwD  / 2 / ma.n_dim;
D{2,2} =  mean(brwD) / 2 / ma.n_dim;
D{2,3} =   std(brwD) / 2 / ma.n_dim;

% Combined diffusions
D{3,1} =      [brwD;subD]  / 2 / ma.n_dim;
D{3,2} = mean([brwD;subD]) / 2 / ma.n_dim;
D{3,3} =  std([brwD;subD]) / 2 / ma.n_dim;

fprintf('Mean Brown. Alpha = %.3g ± %.3g (mean ± std, N = %d)\n', alpha{2,2}, alpha{2,3}, length(alpha{2,1}));
fprintf('Mean Brown. Diffusion = %.3g ± %.3g (mean ± std, N = %d)\n', D{2,2}, D{2,3}, length(D{2,1}));

%% Plot log(MSD)s
if PLOT_MSD_SUBDIFF
    subPlotIndex = find(idx_subdiff & idx_good);
    figure(1); subLines = ma.plotMSD(gca, subPlotIndex(1:50));
    set(gca,'XScale','log','YScale','log');
    set(subLines, "Color", "blue");
    title("Subdiff. MSDs");
end

if PLOT_MSD_BROWNIAN
    brownPlotIndex = find(idx_brown & idx_good);
    figure(1); brownLines = ma.plotMSD(gca, brownPlotIndex(1:100));
    set(gca,'XScale','log','YScale','log');
    set(brownLines, "Color", "red");
    title("Brownian MSDs");
end

%% Plot mean(MSD)s
if PLOT_MEANMSD_SUBDIFF
    figure; ma.plotMeanMSD(gca, true, find(idx_subdiff & idx_good));
    set(gca,'XScale','linear','YScale','log');
    title("Subdiff. mean(MSD)s");
end

if PLOT_MEANMSD_BROWNIAN
    figure; ma.plotMeanMSD(gca, true, find(idx_brown & idx_good));
    set(gca,'XScale','linear','YScale','log');
    title("Brownian mean(MSD)s");
end

%% Plot histogram + fit
if HIST_DIFFUSION
    figure; hold on;
    filteredSubdiff = D{1,1} > 1e-3; % filter out Ds
    filteredBrown   = D{2,1} > 1e-3;
    hist1 = histogram(D{1,1}(filteredSubdiff),'Normalization','probability','FaceColor','b');
    hist2 = histogram(D{2,1}(filteredBrown),'Normalization','probability','FaceColor','r');
    hist1.BinWidth = hist2.BinWidth;
    % histD.NumBins = histD.NumBins * 2;

    % Calculate fit
    % binCenters = hist1.BinEdges(1:end-1) + diff(hist1.BinEdges) / 2;
    % fitOpts = fitoptions('gauss2','Lower',[0 -Inf 0 0 -Inf 0]);
    % fitOpts.Upper = max(hist1.Values) * ones(1,6);
    % histFit = fit(binCenters', hist1.Values', 'gauss2', fitOpts);
    % plot(histFit);

    ylabel("Frequency of Observations");
    xlabel({"Subdiffusion Diffusion Coefficients (um^2/s)", ...
             ((D{1,2} / 1e6) + " ± " + (D{1,3} / 1e6) + " (mean ± std, N = " + length(D{1,1}) + ")"), ...
            "Brownian Diffusion Coefficients (um^2/s)", ...
             ((D{2,2} / 1e6) + " ± " + (D{2,3} / 1e6) + " (mean ± std, N = " + length(D{2,1}) + ")")});
    title("Normalized Diffusions"); box
end